### ISSUE TITLE
package bindings

### ISSUE THREAD

**Issue by deltaworld** [AdobeDocs/adobeio-runtime#39]
The documentation Package Bindings https://www.adobe.io/apis/experienceplatform/runtime/docs.html#!adobedocs/adobeio-runtime/master/guides/using_packages.md#package-bindings
when you invoke `wsk action invoke --result helloMyName/hello` it does not produce `
```json
{
  "payload": "Hello <your name>"
}
instead it produces
{
  "payload": "Hello Christine"
}
```
I can understand why this happens as the default parameter from the previous setting in the documentation sets the default parameter to the action hence why it has a priority, but from a documentation flow perspective this can be seen as confusing.

This overrides the default parameter for the package `hellopackage` but if there is a default parameter set for the action nested within the package, that still takes priority to the one set by the binding. In OpenWhisk there is no way to `bind` to actions but only to packages and this can become problematic as you can’t delete default parameters on actions or packages to that matter

**Comment by mcorlan** [comment]
Thanks a lot for the feedback! I've updated the docs to reflect this. Let me know if this works!
