### ISSUE TITLE
Error: 403 - {"errorcode": "403003", "message": "API Key is Invalid"}

### ISSUE THREAD

**Issue by shridharsahucequity** [AdobeDocs/adobeio-runtime#5]
Hi,

I am trying to set up  enviornment for aio and wsk using cli.
while using **aio console:list-integrations** command I am getting following error

![image](https://user-images.githubusercontent.com/34329066/50766947-1a318b80-12a1-11e9-93cb-3c5089507466.png)

Also i have checked private.key  it works fine in adobe.io console. 
Please help.

Regards,
Shridhar

**Comment by purplecabbage** [comment]
This looks like you are missing the api key.
<img width="357" alt="Screen Shot 2019-07-31 at 5 56 49 PM" src="https://user-images.githubusercontent.com/46134/62257959-f65ca100-b3bc-11e9-8d80-02f42c4dc434.png">
You can set it in your config by running `aio config set jwt-auth.client_id xxxx...`

**Comment by repl-bhoopesh-k** [comment]
Hi Team,

Also I am getting same error. Please help me to resolve this error.
I am generating token by url: https://ims-na1.adobelogin.com/ims/token/v2 in postman with
API: Adobe Photoshop API, scope:openid, AdobeID, read_organizations.

user list url: https://usermanagement.adobe.io/v2/usermanagement/users/{orgid}/{pageno}
Error Message: {"error_code": "403003","message": "Api Key is invalid"}

documents reference:
https://adobe-apiplatform.github.io/umapi-documentation/en/api/getUsersWithPage.html

Code Link:
https://github.com/adobe-apiplatform/umapi-documentation/blob/master/samples/get_users_in_org.py

Thanks in advance

Regards,
Bhoopesh Kumar
