### ISSUE TITLE
Update Runtime regions doc

### ISSUE THREAD

**Issue by gribbletog** [AdobeDocs/adobeio-runtime#66]
Hola! Looks like the Runtime regions doc needs to be updated. I know we have a data center in Australia but I don't have the specifics.

https://www.adobe.io/apis/experienceplatform/runtime/docs.html#!adobedocs/adobeio-runtime/master/reference/multiple-regions.md

**Comment by mcorlan** [comment]
Fixed. Thank you for raising the issue!

**Comment by gribbletog** [comment]
Awesome! Thanks for updating!
